source 'http://rubygems.org'

ruby '2.3.3'

gem 'sinatra'
gem 'selenium-webdriver'
gem 'rake'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'shotgun'
gem 'rspec'
gem 'rspec-sinatra'
gem 'capybara'
gem 'rubocop-rspec'
gem 'rubocop'
gem 'coveralls'
gem 'database_cleaner'
gem 'pg'
gem 'bcrypt'
